import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Head from "next/head";
import HomeBanner from "./components/HomeBanner";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <meta name="referrer" content="no-referrer"></meta>
       <body className={inter.className}>
       <Header />
        {children}
      <Footer />
      {/* <Head> <Header /> </Head> */}
      </body>
     
    </html>
  );
}
